[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.0.0-rc.4" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
selene = { source = "Kampfkarren/selene", version = "*" }
